### ISSUE TITLE
`runningTitle` or `header` ?

### ISSUE THREAD

**Issue by Jean-Baptiste-Camps** [SegmOnto/Guidelines#15]
Which one should we use ? Broader one ?

**Comment by Jean-Baptiste-Camps** [comment]
I move to keep runningTitle.
@gabays et @ArianePinche ?

**Comment by ArianePinche** [comment]
runningTitle is ok for me

**Comment by gabays** [comment]
running title est dans Muzerelle, l'autre pas.
