### ISSUE TITLE
`Numbering`

### ISSUE THREAD

**Issue by Jean-Baptiste-Camps** [SegmOnto/Guidelines#16]
Should we amend the description to specify what we are numbering ? Not only page numbers, actually. 

- Only physical ?
- Logical ?
- Only independent zones ?

**Comment by Jean-Baptiste-Camps** [comment]
I move to stick to page numbers.

@gabays et @ArianePinche ?

**Comment by ArianePinche** [comment]
pageNumbers seems easier to use.

**Comment by gabays** [comment]
Oui mais l'idée était de mettre aussi la numérotation de cahier dedans non?

**Comment by Jean-Baptiste-Camps** [comment]
Good point, but I would stick to `quire-marks` for things regarding the quires.

**Comment by Jean-Baptiste-Camps** [comment]
In any case, we could add an open `subtype` list, with page being the default.
