### ISSUE TITLE
`default` line

### ISSUE THREAD

**Issue by gabays** [SegmOnto/Guidelines#17]
Should we create a specific kind of line for anything that is not in main. With different names, we would help the system. It would be similar than interlinear lines. Cf. Daniel's example:

<img width="373" alt="Screenshot 2021-05-06 at 17 31 03" src="https://user-images.githubusercontent.com/26046460/117325311-e080e780-ae90-11eb-93a9-3d3ed1efaa69.png">

**Comment by Jean-Baptiste-Camps** [comment]
I move to stick to default. It is not the ontology's role to fix (current) software limitations.
@gabays and @ArianePinche ?

**Comment by ArianePinche** [comment]
I'm not sure it's a good idea to keep only "default": first, from a pragmatic point of view, we have to change the name for each line considering the basic segmentation model of Kraken. I would prefer something like main, margin, annotation (easier for the computer and logical for humans).

**Comment by gabays** [comment]
Proposition: un système de suffixe? De la même manière qu'un numérotation (main1, main2…) pourrait aider le système sans dévoyer le principe d'un vocabulaire contrôlé

**Comment by Jean-Baptiste-Camps** [comment]
The thing I'm proposing (in the slides) is to have an open `subtype` for everything, with only suggested values, apart from the main (closed list) `type`. This way, we can suggest a bunch of subtypes, but leave it open for the user to add their own. 

The other point is the redundancy between lines and zones. `margin` is a type of zone, so implicitly the lines inside it are marginal lines (but "default" marginal lines, in the sense that you can also have interlinear lines in a marginal addition, right ?).

**Comment by gabays** [comment]
Last moment to rename `default`, which is way too close to `Default` in _Kraken_ and can create problems when reading results. Why not, for the sake of clarity:
* `MainLine`
* `MusicNotationLine` (ou `Music` et `MusicLine`, parce qu'il pourrait y avoir quoi d'autre qu'une _notation_ de _Music_)
* `DropCapitalLine`
* `InterlinearLine`
* `RubricLine`

**Comment by Jean-Baptiste-Camps** [comment]
Just to make sure: we are talking about the `Default` line type, right (`default` does not exist, I think) ?

Basically, for now, we have:

- `Default`
- `DropCapitalLine`
- `Interlinear`
- `MusicLine` (actually musical notations usually contains both notes on a stave (`MusicLine`) and text (`Default`)
- `Rubric`

We can use subtypes to Default if necessary (like `Default:Main`, or even `Default:Main#1` if necessary as in #21).

With that said, I wonder if we couldn't actually dispense with the `DropCapitalLine`. That would be

- `Default`
- `Interlinear`
- `MusicLine` (or `Stave` to be clearer)
- `Rubric`

**Comment by gabays** [comment]
Adding `line` is a way to make clear it is a two-tear ontology: _zone_ and _line_. Like `title` vs `titleStmt`, or `Name`in `placeName`, `orgName`. It is not crucial, but it says something important. I would actually not mind adding `zone` to the zones, for the sake of clarity.

I see a big problem with `Default`: it is that when Kraken has a problem with a line, it calls the line `default`. Too me, the name is already used and I would drop it.

And you want to get rid of `DropCapitalLine`?

**Comment by Jean-Baptiste-Camps** [comment]
> I see a big problem with Default: it is that when Kraken has a problem with a line, it calls the line default. Too me, the name is already used and I would drop it.

But isn't that exactly what we want: the `default/Default` untyped line ?

**Comment by Jean-Baptiste-Camps** [comment]
I see the point in adding `-Line` or `-Zone` everywhere, but it is very verbose (and tools like eScriptorium clearly distinguish both types).

**Comment by Jean-Baptiste-Camps** [comment]
If I go back to your original idea, then we would have something like:

- `Main` lines
- `Peripheral` lines (?)
- `Interlinear` lines

my question: a regular line in a gloss, marginal addition, etc. Is it `Main` (because a `Main` line of the addition) or `Peripheral` (because in the margin). I would vouch for the first in this case, because you can have interlinear or peripheral lines in additions too.

**Comment by gabays** [comment]
Good remark. Too me it is just a lexical problem. So why not `standard` then? There could be a `standardLine` in `main` or in `margin`, no?

**Comment by Jean-Baptiste-Camps** [comment]
Go `DefaultLine`

**Comment by gabays** [comment]
Problem solved: we now have [DefaultLine](https://github.com/SegmOnto/Guidelines/tree/main/lines/DefaultLine).
