### ISSUE TITLE
Additional elements

### ISSUE THREAD

**Issue by gabays** [SegmOnto/Guidelines#18]
Daniel proposes to add new elements:
1. shelfmark
2. ruler
3. color table

**Comment by PonteIneptique** [comment]
I don't know if ruler is what I believe, but I'd recommend having a `DigitizationArtefact` zone, including rules, color tables on the side, etc.

**Comment by gabays** [comment]
It was his idea. @Jean-Baptiste-Camps also proposed a private zone, following a discussion we had on entries and paragraphs

**Comment by PonteIneptique** [comment]
The reason why I'd recommend having a broader kind of zone is exactly the one that was pushed in https://github.com/SegmOnto/examples/issues/19 . It makes the number of zone smaller, it can include a broader set of elements (thumbs ? cat paws ?) and if someone is really interested in researching digitization artifact, they can then tag them with their own ontology :D
