### ISSUE TITLE
Recommandation for `subzoning` and `numerotation`

### ISSUE THREAD

**Issue by PonteIneptique** [SegmOnto/Guidelines#21]
Hey there,
I was thinking about #19 and some of the issues we have with segmenters here and there to make a difference between two columns.

As such, I'd recommend to follow a syntax such as `MainZoneName(:SubZoneName)?(#Numerotation)`:
- `Margin:CriticalApparatus#1` and `Margin:CriticalApparatus#2`
- `Main#1` (when dealing with columns)
- `Main:Column#2` (same)

`#` is fairly common to mark separation and `:` as well. I'd reserve `:` for the identification itself, and `#` for comment-like information such as numbering

**Comment by gabays** [comment]
I agree, and mentioned your idea during today's meeting (giving you the credits for it, obviously) ;-)

**Comment by gabays** [comment]
Can I close this issue if we agree?

**Comment by PonteIneptique** [comment]
Only if it is formalized in the doc, only if it is formarlized in the doc...

![](https://media.giphy.com/media/0DYipdNqJ5n4GYATKL/giphy.gif)

**Comment by Jean-Baptiste-Camps** [comment]
@gabays , when I said we should work collaboratively more on Github because it would made for more transparent and better code, what I actually meant was that @PonteIneptique was going to check and comment every of our issues and PR :eyeglasses:

**Comment by PonteIneptique** [comment]
Someone needs to keep you in check.
(or invested in segmonto and things to get well😊)

**Comment by gabays** [comment]
Done by JB. Cf. https://github.com/SegmOnto/Guidelines/blob/main/README.md
