### ISSUE TITLE
`subtype` list

### ISSUE THREAD

**Issue by gabays** [SegmOnto/Guidelines#22]
In any case, we could add an open `subtype` list, with page being the default.

_Originally posted by @Jean-Baptiste-Camps in https://github.com/SegmOnto/examples/issues/16#issuecomment-957658992_

**Comment by gabays** [comment]
* Decoration
  1. illustration
  2. ornament
* Margin
  1. side
  2. bottom
  3. criticalApparatus
* QuireMarks
  1. signature
  2. numbering
* DropCapital
  1. historiated
  2. flourished

Vous me dites et je complète la liste

**Comment by Jean-Baptiste-Camps** [comment]
- QuireMarks : catchwords (pas sûr que numbering soit nécessaire, car fait partie de la signature ?);
- Decoration: Ornement -> Ornementation (to keep it consistent ?)
- subtype `guide` (`d'attente` for DropCapital, RunningTitle)
- For DropCapital: a look at http://codicologia.irht.cnrs.fr/theme/liste_theme/561#tr-5588
- Damage: hole, humidity ?, (perhaps look at: http://codicologia.irht.cnrs.fr/theme/showcat/73)
- Numbering: page, other,
- Stamp: postal, curatorial

**Comment by gabays** [comment]
* Decoration
  1. illustration
  2. ornementation
* Margin
  1. side
  2. bottom
  3. criticalApparatus
* QuireMarks
  1. signature
  2. catchwords
* DropCapital (http://codicologia.irht.cnrs.fr/theme/liste_theme/561)
  1. historiated
  2. flourished
  3. guide
* Damage (cf. http://codicologia.irht.cnrs.fr/theme/showcat/73)
  1. hole
  2. water
* Numbering
  1. page
  2. folio
  3. other
* Stamp
  1. postal
  2. curatorial

Vous me dites et je complète la liste

**Comment by gabays** [comment]
cf. https://github.com/SegmOnto/examples/pull/23
