### ISSUE TITLE
Should `Figure` be kept distinct from `Decoration` or become a subtype ? 

### ISSUE THREAD

**Issue by Jean-Baptiste-Camps** [SegmOnto/Guidelines#25]
Everything is in the title. It is not always possible (or a need) to distinguish figures from decoration (e.g., ornemented genealogical trees, etc., in medieval mss).

**Comment by gabays** [comment]
A figure is not a decoration. I don't mind merging the two and making it a subtype, but we need to rename the zone. `figure` is the term chosen by the TEI and LaTeX if I remember well. Or `graphicZone`

**Comment by Jean-Baptiste-Camps** [comment]
Yes, I know, but Frederic's point on that was good: figure can be heavily ornemented, etc. I have no strong opinion on any solution (though I agree with the `Decoration` and `Figure` distinction on principle).

**Comment by gabays** [comment]
Let's make all this a bunch of `graphicZone:subtypes`?  (if we keep `graphicZone`)

**Comment by gabays** [comment]
Solved. Cf. https://github.com/SegmOnto/Guidelines/tree/main/zones/GraphicZone
