### ISSUE TITLE
Should `Title` be kept ?

### ISSUE THREAD

**Issue by Jean-Baptiste-Camps** [SegmOnto/Guidelines#26]
It is more semantic than layout, and so is partly out of the system.

**Comment by gabays** [comment]
Yes, but it is super easy to recognise (the main problem why we avoid semantic stuff) and super convenient for prints. I would make an exception. Probably rename `TitlePage` though, to make it clear

**Comment by Jean-Baptiste-Camps** [comment]
Ok, `TitlePage` seems nice.

**Comment by gabays** [comment]
cf #28
