### ISSUE TITLE
Colophon

### ISSUE THREAD

**Issue by PaulineJac** [SegmOnto/Guidelines#36]
What designation would you suggest for zone with a colophon as in this example?  
<img width="582" alt="image" src="https://user-images.githubusercontent.com/61355979/144065695-ac1a06db-e1cb-43c0-bb0c-cd8f413eb495.png">

**Comment by Jean-Baptiste-Camps** [comment]
Hello,
For me, it is part of the `MainZone` (it is a semantic distinction, but not a layout distinction).

**Comment by Jean-Baptiste-Camps** [comment]
Ah, sorry, you meant the colophon at the end of the page, not the ex-libris (_Es proprietat…_).

Good question: is it `MarginTextZone` or `QuireMarksZone` ?

**Comment by gabays** [comment]
For the printer at the very bottom, I would use `MarginTextZone` possibly combined with `:colophon`. It does not describe _the material organisation of the source_ (our definition), but rather its material production/provenance.

**Comment by PaulineJac** [comment]
Thank you for your answers.
My question was indeed about this whole thing :  the "ex-libris", but also the mention of the place of sale ( en la casa Joan Grau...), and the colophon _stricto sensu_ ( REUS: IMP. Y LIB. ... ). 

- For the copyright mention, in this example, it could be part of the `MainZone`.
However, in my corpus, this mention can be alone on a whole page: 
<img width="392" alt="image" src="https://user-images.githubusercontent.com/61355979/144102710-0134e861-d0e6-4c7f-ac0a-afa5ab976a41.png">

- For the mention of the place of sale I also have such examples of this type in my corpus: 
<img width="360" alt="image" src="https://user-images.githubusercontent.com/61355979/144103551-1df96857-a34d-4713-a2f1-e9769f1d0b28.png">
I think it would be interesting to dissociate also this part from the  `MainZone`.

- For the colophon, I note the solution proposed by @gabays. 

Thank you for your help.

**Comment by gabays** [comment]
- Image1: Anything that is semantic is not taken into account: _en la casa…_ or the _ex libris_ should not be encoded with SegmOnto. It goes into `MainZone`. the information about the printer are clearly separated from the rest, so it is in the _margin_->`MarginTextZone`
-  Image 2: For the "copyright" it should be a `GraphicZone:decoration`, containing a `DefaultLine`, I think. We do not say it is a copyright, we just indicate it is decorated. Nothing semantic again ;-)
- Image 3: For the last question, is it the title page? If yes, it goes into `TitlePageZone`

**Comment by PaulineJac** [comment]
Indeed, the last example is a title page, but there are similar situations on the last page; I guess in this case it will have to be included in the `MainZone`. 
Thanks for the "copyright" solution and for your help.

**Comment by gabays** [comment]
Ca we reuse the images in our examples?

**Comment by PaulineJac** [comment]
Yes, it is possible to reuse these images by quoting the source: 
Bibliothèque Universitaire de Genève, 
https://unige.swisscovery.slsp.ch/discovery/fulldisplay?docid=alma991008229029705502&context=L&vid=41SLSP_UGE:VU1&lang=fr&search_scope=MyInst_and_CI&adaptor=Local%20Search%20Engine&tab=4
