### ISSUE TITLE
Change `RubricLine` to `HeadingLine`?

### ISSUE THREAD

**Issue by gabays** [SegmOnto/Guidelines#39]
Following a long debate during the workshop yesterday, we all thought that:
- `RubricLine` is too manuscript related
- `HeadingLine` would be more appropriated (french _titraille_?), or maybe `HeadLine`
- potential values for the subtypes could be `:rubric`, `:chapter`…

Other option: `HighlithedLine` for the lines with a different color or font (bold, italics…)

This question is linked to this issue: https://github.com/SegmOnto/Guidelines/issues/38

**Comment by Jean-Baptiste-Camps** [comment]
Well, this was supposed to be a manuscript layout analysis ontology, wasn't it ^^ ? But, yes, `headingLine` or `titleLine`, why not.

**Comment by gabays** [comment]
You are right, but its purpose kind of changed in the meantime… I prefer `headingLine` to avoid misunderstanding with `TitlePage` and other stuff related to titles
